### ISSUE TITLE
Negative Rates

### ISSUE THREAD

**Issue by Asagodi** [choderalab/openpathsampling#390] opened 2015-11-22 19:22 UTC
Is there some progress on the issue with the negative rates (when the wrong outer lambda is determined)?

Should the Lookup function maybe return an Error when a negative rate is found? Or should it return zero?

**Comment by dwhswenson** [comment] 2015-11-23 10:49
Could you make a gist with a notebook that gives an example of the problem? Make sure it includes a complete analysis -- in particular, I would need to see the results of the "Interface crossing probabilities" section under "Path ensemble properties." It is hard for me to do anything about this otherwise. I've only seen this problem occur when there is insufficient data to get a reasonable estimate of the rate.

The only other case I can think of where this might happen is if you have interfaces that have 100% of trajectories going into a given other state. In that case, you should remove that interface: it doesn't give you any information anyway, and is just costing you computational time.

LookupFunction should not be changed. That's just a way to turn a discrete data set into a continuous function. The problem is in the generation of the input to the LookupFunction -- in particular, the problem is in the automatic identification of lambda for the outermost interface.

I'll also put together a small PR to add some logging information for the analysis process. If you have a case where this happens, please keep the .nc file around so you can redo the analysis with updated versions of the code and tell us if we've fixed it.

**Comment by dwhswenson** [comment] 2015-11-23 12:55
@Asagodi : As soon as #392 is merged in, you should get that version of the code and try with that. I made a small change that might fix the problem (using almost-equals instead of equals, just in case there's rounding error) and I added some logging.

If you enable logging during your analysis, it will report what it has selected as the outermost lambda. Knowing what value it is picking will help identify why it isn't picking the correct value.

See the mstis notebook for a (commented out) example of how to enable logging. That will also require a logging conf file (one is located in the examples/ipython directory).

**Comment by Asagodi** [comment] 2015-11-24 11:05
https://gist.github.com/Asagodi/465f459710bbfa58dee6#file-3c_d_02-ipynb

The trick to get around the rounding errors worked with an interval of 1\pm 10^-15 in all cases.

**Comment by Asagodi** [comment] 2015-11-26 08:44
Here is a simulation with even more runs and samples

https://gist.github.com/Asagodi/5d34bda44a1bf6cb27db#file-mstis_analysis3-ipynb

**Comment by dwhswenson** [comment] 2015-11-27 18:54
Are these running with versions of the code updated after #392? The rounding error problem should be impossible after that one.

Also, please add logging and include the output from the logger (in a .log file). That will tell what the code is actually doing. See the commenting logging stuff `mstis.ipynb` for an example of setting up logging.

**Comment by Asagodi** [comment] 2015-12-02 08:02
This one is with the version after #392.
Strangely the .log file created by the script is empty

**Comment by bolhuis** [comment] 2015-12-15 20:22
I still think that basing the interface lambda on the actual values in the histograms is very dangerous and will always lead to trouble.  E.g. some ensembles might have only large max values leading to errors in the determination of the interface values. The solution is IMHO to use information of the network to extract these values. After all this info is already there, not?

**Comment by jhprinz** [comment] 2016-03-04 22:00
Can this be closed? Or is it still an issue?

**Comment by dwhswenson** [comment] 2016-03-05 06:57
I think so. It looked to me like @Asagodi's continuing problems with this were due to having a bad version of OPS in his path. (He was getting none of the new features we added to the code.) This should have been fixed in #392.

**Comment by jhprinz** [comment] 2016-03-05 10:09
Alright. Then I will close this.

**Closed by jhprinz** 2016-03-05 10:09 UTC
Labels: closable?
