### ISSUE TITLE
Bug in PathReversalMover

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#141] opened 2015-02-02 14:02 UTC
There seems to be a problem in PathReversalMover. I notice this when doing the TIS equilibration in the toy model. I get weird paths that appear to have kinks in them. Here is an egregious example:

![awv2feubgkybaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/8178546/5999311/ee306cd6-aad0-11e4-9e2a-e12ce2395df5.png)

The contour lines are at intervals of $k_B T$, so that reversal on the right hand side is pretty significant.

If I turn off path reversals as part of the equilibration (set the `root_mover=shooting_choser`), I don't see these paths. My guess is that maybe something weird is going on with the interactions of path reversals and shooting moves, or that something is wrong with the generation of reversed trajectories.

I think the best way to explore this will be to use an IPython notebook similar to the toy model notebook, and check step-by-step how the path changes.

**Comment by jhprinz** [comment] 2015-02-02 16:44
We should check, if the reversal is implemented correctly so that it really does a correct copy and not overwrites existing velocities with the reversed ones. I had a similar problem before. Let me see, if I can find the cause...

**Comment by jhprinz** [comment] 2015-02-05 17:37
This is fixed in PR #125.

**Closed by jhprinz** 2015-02-05 17:37 UTC
